import casual.make.api as make
import casual.middleware.make.api as dsl

make.IncludePaths([
    'include',
    'unittest/include',
    '../common/include',
    '../xatmi/include',
    ]    
    + make.optional_include_paths()
    + dsl.paths().include.gtest
   )

make.LibraryPaths(
   [
      'bin',
      '../common/bin',
   ]
    + make.optional_library_paths()
    + dsl.paths().library.gtest
   )

# we can use an archive for casual-manager, since it's only used in
# 'managers'
# @attention: do not link this archive in a lib, only executables
manager_archive = make.LinkArchive( 'bin/casual-manager', 
   [
      make.Compile( 'source/service/context.cpp'),
      make.Compile( 'source/service/handle.cpp'),
      make.Compile( 'source/service/policy.cpp'),
      make.Compile( 'source/service/protocol.cpp'),
      make.Compile( 'source/service.cpp'),
   ]
)

make.LinkUnittest( 'bin/test-casual-manager',
   [
        make.Compile( 'unittest/source/test_manager.cpp'),
   ],
   [
      manager_archive,
      'casual-common',
      'casual-unittest',
   ]
)


