import casual.make.api as make
import casual.middleware.make.api as dsl

make.IncludePaths([
    'include',
    'unittest/include',
    '../common/include',
    '../xatmi/include',
    ]    
    + make.optional_include_paths()
    + dsl.paths().include.gtest
   )

make.LibraryPaths(
   [
      'bin',
      '../common/bin',
   ]
    + make.optional_library_paths()
    + dsl.paths().library.gtest
   )

install_libs = []

manager_lib = make.LinkLibrary( 'bin/casual-manager', 
   [
      make.Compile( 'source/service/context.cpp'),
      make.Compile( 'source/service/handle.cpp'),
      make.Compile( 'source/service/policy.cpp'),
      make.Compile( 'source/service/protocol.cpp'),
      make.Compile( 'source/service.cpp'),
   ],
   [
      'casual-common',
      'casual-common-serialize-service',

   ]
)

install_libs.append( manager_lib)

make.LinkUnittest( 'bin/test-casual-manager',
   [
        make.Compile( 'unittest/source/test_manager.cpp'),
   ],
   [
      manager_lib,
      'casual-common',
      'casual-unittest',
   ]
)

make.Install( install_libs, dsl.paths().install + '/lib')

