

INCLUDE_PATHS= include \
	../common/include \
	../utility/include \
	../xatmi/include
	
LIBRARY_PATHS= ../xatmi/bin \
	../common/bin \
	../utility/bin



Compile( source/template_server.cpp, obj/template_server.o)

LinkAtmiServer(test, \
	obj/template_server.o, \
	casual-xatmi, \
	"casual_test1,casual_test2")
	
	
Compile( source/template_client.cpp, obj/template_client.o)

LinkExecutable( test_client, \
	obj/template_client.o, casual_common casual_utility)
