

Include( $(CASUAL_BUILD_ENVIRONMENT))


INCLUDE_PATHS= include \
	../common/include \
	../utility/include \
	../serviceframework/include \
	../xatmi/include \
	$(YAML_INCLUDE_PATH) \
    $(UNITTEST_INCLUDE_PATH) \
	
LIBRARY_PATHS= ../xatmi/bin \
	../common/bin \
	../utility/bin \
	../serviceframework/bin \
	$(YAML_LIBRARY_PATH)



Compile( source/template_server.cpp, obj/template_server.o)


LinkAtmiServer(test, \
	obj/template_server.o, \
	casual-xatmi casual_utility, \
	"casual_test1,casual_test2")


/*
Compile( source/template_server_dispatcher.c, obj/template_server_dispatcher.o)

LinkExecutable(test, \
    obj/template_server_dispatcher.o \
    obj/template_server.o, \
    casual-xatmi casual_utility)	
*/	


//
// Compile and link VO:n
//
Compile( source/sf_testvo.cpp, obj/sf_testvo.o)

LinkArchive( sf_test_vo, \
    obj/sf_testvo.o)


//
// compile and link the sf-template-server
//
Compile( source/template_sf_server.cpp, obj/template_sf_server.o)
Compile( source/template_sf_server_implementation.cpp, obj/template_sf_server_implementation.o)

LinkAtmiServer(sf_test, \
    obj/template_sf_server.o \
    obj/template_sf_server_implementation.o, \
    sf_test_vo \
    casual-xatmi \
    casual_utility \
    casual_sf, \
    "casual_sf_test1,casual_sf_test2")


	
Compile( source/template_client.cpp, obj/template_client.o)

LinkExecutable( test_client, \
	obj/template_client.o, casual_common casual_utility casual-xatmi)
	



Compile( source/test_multicall.cpp, obj/test_multicall.o)

LinkExecutable( test_multicall_client, \
	obj/test_multicall.o, casual_common casual_utility casual-xatmi)
	
	
	
//
// unittest
//
Compile( unittest/isolated/source/test_yaml_sf_generation.cpp, unittest/isolated/obj/test_yaml_sf_generation.o)



LinkIsolatedUnittest( casual_test_isolated, \
    unittest/isolated/obj/test_yaml_sf_generation.o, \
    casual_sf casual-xatmi)
	
	
	
