#!/bin/bash

set -e
#dirname $0 > /tmp/slask.$$
export CASUALMAKE_PATH=$( dirname $0 )
#
# Definera realiseringen.
#
IMPLEMENTATION_PATH="$CASUALMAKE_PATH/implementation"

ENGINE="$IMPLEMENTATION_PATH/engine";
HELP="$IMPLEMENTATION_PATH/help";

FUNCTION_DEFINITIONS="$IMPLEMENTATION_PATH/function_definitions";

PREPARE_FUNTIONS="$IMPLEMENTATION_PATH/prepare_function_definitions";
IMAKE_NORMALIZE="$IMPLEMENTATION_PATH/normalize_imakefile";

export AWK=awk

if [[ "$1" == "-help" || "$1" == "-h" || "$1" == "-?" ]]
then
	$HELP "$FUNCTION_DEFINITIONS" "$PREPARE_FUNTIONS" ${@:2}
	exit 0
fi

#
# Select supported plattforms
#
export CASUAL_OS=$( uname -s | tr [:upper:] [:lower:] )
if [[ $CASUAL_OS == "darwin" ]]; then
	SUFFIX="osx"
elif [[ $CASUAL_OS == "linux" ]]; then
	SUFFIX="linux"
else
	SUFFIX="solaris"
fi
CONFIG="$IMPLEMENTATION_PATH/config_"$SUFFIX

USER_CASUAL_MAKE_FILE=$1;

#
# Kolla om användaren har skickat med någon imake/make-fil
#
if [[ "$USER_CASUAL_MAKE_FILE" == "" ]]
then
   echo "info: Using default: makefile.cmk" > /dev/stderr;
   USER_CASUAL_MAKE_FILE="makefile.cmk";
fi

if [[ ! -f "$USER_CASUAL_MAKE_FILE" ]]
then
   echo "error: Failed to open file: $USER_CASUAL_MAKE_FILE" > /dev/stderr;
   exit 1;
fi


USER_MAKE_FILE="${USER_CASUAL_MAKE_FILE%.*}".mk


echo "info: generates $USER_MAKE_FILE from $USER_CASUAL_MAKE_FILE"   
#
# Starta motorn
#
$ENGINE $FUNCTION_DEFINITIONS $CONFIG $PREPARE_FUNTIONS $IMAKE_NORMALIZE $USER_CASUAL_MAKE_FILE $USER_MAKE_FILE;

exit $?


