

Build( common/makefile.cmk)
Build( xatmi/makefile.cmk)

Build( serviceframework/makefile.cmk)

Build( test/makefile.cmk)

Build( broker/makefile.cmk)
Build( monitor/makefile.cmk)

Build( transaction/makefile.cmk)

