

from casual.make.functiondefinitions import *

Include( "$(CASUAL_BUILD_ENVIRONMENT)")

IncludePaths( [
   "../common/include",
   "../xatmi/include",
   "$(UNITTEST_INCLUDE_PATH)",
   ])


LibraryPaths([
    "../common/bin",
    "../xatmi/bin",
    "$(JSON_LIBRARY_PATH)",
    ])


Compile( "source/string.cpp", "obj/string.o")
Compile( "source/octet.cpp", "obj/octet.o")
Compile( "source/order.cpp", "obj/order.o")
Compile( "source/field.cpp", "obj/field.o")

LinkLibrary( "bin/casual-buffer",
    [
     "obj/string.o",
     "obj/octet.o",
     "obj/order.o",
     "obj/field.o"
    ],
    [
     "casual-common",
    ])



#
# Unittest
#
Compile( "unittest/isolated/source/test_field_buffer.cpp", "unittest/isolated/obj/test_field_buffer.o")
Compile( "unittest/isolated/source/test_octet_buffer.cpp", "unittest/isolated/obj/test_octet_buffer.o")
Compile( "unittest/isolated/source/test_order_buffer.cpp", "unittest/isolated/obj/test_order_buffer.o")
Compile( "unittest/isolated/source/test_string_buffer.cpp", "unittest/isolated/obj/test_string_buffer.o")

LinkIsolatedUnittest( "bin/test-buffer",
   [
    "unittest/isolated/obj/test_octet_buffer.o",
    "unittest/isolated/obj/test_order_buffer.o",
    "unittest/isolated/obj/test_string_buffer.o",
    "unittest/isolated/obj/test_field_buffer.o",
   ],
   ["casual-common", "casual-xatmi", "casual-buffer"])  
   
#
# Install
#
InstallLibrary("bin/casual-buffer", "$(CASUAL_HOME)/lib/.")



