#!/usr/bin/python



#
# Imports
#
import sys
import os
import errno
import subprocess
import optparse
import re
import signal

from functools import partial


class  Color:
    
    __grey = '\033[30'
    
    __red = '\033[31'
    
    __green = '\033[32'

    __yellow = '\033[33'
    
    __blue = '\033[34'
    __magenta = '\033[35'
    
    __pink = '\033[0;1;35m'
    
    __cyan = '\033[36'
    __white = '\033[37'
    __error = '\033[91'
    
    __WARNING = '\033[0;23m'
    
    __ENDC = '\033[0m'
    
    
    def __bold(self, string, bold = False):
        if bold:
            return string + ';1m'
        else:
            return string + 'm';
    
    def grey( self, string, bold = False):
        return self.__bold( self.__grey, bold) + string + self.__ENDC
    
    def header( self, string):
        return self.__magenta + string + self.__ENDC
    
    def red( self, string, bold = False):
        return self.__bold( self.__red, bold) + string + self.__ENDC
    
    def blue( self, string, bold = False):
        return self.__bold( self.__blue, bold) + string + self.__ENDC

    def green( self, string, bold = False):
        return self.__bold( self.__green, bold) + string + self.__ENDC

    def cyan( self, string, bold = False):
        return self.__bold( self.__cyan, bold) + string + self.__ENDC
    
    def error( self, string):
        return self.__error + string + self.__ENDC
    
    def yellow( self, string, bold = False):
        return self.__bold( self.__yellow, bold) + string + self.__ENDC
    
    def white( self, string, bold = False):
        return self.__bold( self.__white, bold) + string + self.__ENDC
    
    def warning(self, string, bold = False):
        return self.__pink + string + self.__ENDC
    
    def default(self, string, bold = False):
        return string

color=Color()


def time( time):
    return time[0: 11] + color.white( time[11:]);

def domain( name):
    
    if( len( name) > domain.size):
        domain.size = len( name);
    
    return name.ljust( domain.size);
    
domain.size = 0;


def normalizePID( id):
    return id;
    #return id.rjust( 8);
    


def truncateUUID( uuid):
    # take the first 13:
    if uuid:
        return uuid[:13];
    else:
        return '             ';

def truncateXID( xid):
    # 590b07bd-0903-40ec-9faa-2156b90a2756:1c04d1e1-886f-4820-bc9f-fb66ababf7d2
    # -> 2156b90a2756:1c04d1e1
    
    if xid:
        return xid[24: 24 + 21];
    else:
        return '' #'                     ';


def truncateThread( pid, thread):
    
    process = truncateThread.threads.get( pid);
    
    if not process:
        process = truncateThread.threads[ pid] = dict();
    
    threadId = process.get( thread);
    
    if not threadId:
        threadId = process[ thread] = len( process) + 1;
        
    return str( threadId);
    

truncateThread.threads = {};
#truncateThread.count = 0;


def category( name):
    
    for match in category.switch:
        if match[ 0].match( name):
            return match[ 1]( name)
    
    return name;

category.switch = [
    [ re.compile( '^err'), partial( color.red, bold = True)],
    [ re.compile( '^war'), partial( color.warning, bold = True)],
    [ re.compile( '^inf'), partial( color.white, bold = True)],
    [ re.compile( '^deb'), color.green],
    [ re.compile( '^tra'), partial( color.green, bold = True)],
    #[ re.compile( '^casual[.]trace'), color.bold_blue], 
    [ re.compile( '^casu'), color.blue],                
]



def format( input, output):
    
    line = input.readline();
    
    while( line):
        
        rows = line.split( '|', 9);
        
        if( len( rows) == 10):
            
            pid = rows[ 4];
            thread = truncateThread( pid, rows[ 5]);
            
            output.write( time( rows[ 0]));
            output.write( '|');
            output.write( color.default( domain( rows[ 1])));
            output.write( '|');
            output.write( color.yellow( truncateUUID( rows[ 2])));
            output.write( '|');
            output.write( color.default( truncateXID( rows[ 3])));
            output.write( '|');
            output.write( color.white( normalizePID( pid)));
            output.write( '|');
            output.write( thread);
            output.write( '|');
            #output.write( color.white( rows[ 6]));
            output.write( rows[ 6]);
            output.write( '|');
            output.write( category( rows[ 7]));
            output.write( '|');
            output.write( color.yellow( rows[ 8]));
            output.write( '|');

            if rows[ 7] in [ "information", 'error']:
                output.write( color.white( rows[ 9]));
            else:
                output.write( rows[ 9])
            #sys.stdout.write( '\n');
        else:
            output.write( line)
    
        line = input.readline();
    

# def handler(number, frame):
#     sys.stderr.write( "signal: " + str( number) + " received\n");
#     pass;
#     
# 
# def less( input):
#     try:
#         signal.signal(signal.SIGINT, handler)
#         signal.signal(signal.SIGILL, handler)
#         
#         process = subprocess.Popen( ['less', '-r'], stdin=subprocess.PIPE, universal_newlines=True)
#         
#         output = process.stdin;
#         
#         #process.stdin = sys.stdout;
#     
#         format( input, output);
#     
#         process.communicate();
#         
#     except IOError as e:
#         if e.errno != errno.EPIPE:
#             raise
#     


if __name__ == '__main__':

    parser = optparse.OptionParser("""
        usage: %prog [logfile...]
        
        Format of the logfile:
        
        <time>|<domain>|<execution id>|<transaction id>|<process id>|<thread id>|<executable>|<log category>|<service>|<message>...
        
        """)
    
    (options, args) = parser.parse_args()
    
    try:

        if len( args) > 0:
            with open( args[ 0]) as infile:
                format( infile, sys.stdout);
        
        elif not sys.stdin.isatty():
            format( sys.stdin, sys.stdout);
            
        elif os.environ["CASUAL_DOMAIN_HOME"]:
            with open( os.environ["CASUAL_DOMAIN_HOME"] + '/casual.log') as infile:
                format( infile, sys.stdout);
    
    except IOError as e:
        if e.errno != errno.EPIPE:
            raise


