#! /bin/bash

set -e

cd $REPOSITORY_ROOT && \
    casual-make --build-root /tmp/build --stat --quiet --no-colors compile && \
    casual-make --build-root /tmp/build --stat --no-colors link && \
    casual-make --build-root /tmp/build --no-colors test --gtest_color=no --gtest_output='xml:report.xml' && \
    casual-make --build-root /tmp/build --no-colors install && \
    casual-make --build-root /tmp/build nginx
