domain:

  # name of this domain
  name: domainB
      
  # no servers will be started in ths domain    
  servers: 
        
    - alias: nginx
      note: nginx casual style
      path: ${CASUAL_HOME}/nginx/sbin/nginx
      arguments: [-p,"${CASUAL_HOME}/nginx"]
      instances: 1
      

  #
  # gateway configuration
  #
  gateway:
    # we don't configure any listeners, hence don't let any other domain connect.
  
    connections:
      # We connect to domainA
      - address: domainA:7771
        # we "know" that domainA has an echo-service
        services: [ casual.example.echo]
  
