import casual.make.api as make
import casual.middleware.make.api as dsl

import os

make.IncludePaths( [ 
    'include',
    'unittest/include',
    '../common/include',
    '../cli/include',
    '../configuration/include',
    '../configuration/unittest/include',
    '../serviceframework/include', 
    '../xatmi/include',
    '../transaction/include',
    '../domain/include',
    '../domain/unittest/include',
    '../service/include',
    '../../thirdparty/database/include',
    '../service/unittest/include'
    ]
    + make.optional_include_paths()
    + dsl.paths().include.gtest
   )


make.LibraryPaths( [ 
    'bin',
    '../transaction/bin',
    '../configuration/bin',
    '../serviceframework/bin',
    '../common/bin',
    '../cli/bin',
    '../buffer/bin',
    '../domain/bin',
    '../service/bin',
    '../xatmi/bin']
    + make.optional_library_paths()
    + dsl.paths().library.gtest
   )
    



install_lib = []
install_bin = []

# So we get the local build-rm
make.Environment( 'PATH', '../tools/bin' + os.pathsep + os.getenv('PATH'))

# Common stuff

common = make.LinkArchive( 'bin/casual-queue-common',
   [
    make.Compile( 'source/common/log.cpp'),
    make.Compile( 'source/common/queue.cpp'),
    make.Compile( 'source/code.cpp'),
   ])
 
# Group

group_archive = make.LinkArchive( 'bin/casual-queue-group-archive',
[
    make.Compile( 'source/group/state.cpp'),   
    make.Compile( 'source/group/queuebase.cpp'),
    make.Compile( 'source/group/queuebase/statement.cpp'),
    make.Compile( 'source/group/handle.cpp'),
])


queue_group = make.LinkExecutable( 'bin/casual-queue-group', 
[
    make.Compile( 'source/group/main.cpp')
],
[
    group_archive,
    common,
    'casual-domain-utility',
    'casual-common',
    'sqlite3',
])
     
 
install_bin.append( queue_group)
 
# Manager


manager_archive = make.LinkArchive( 'bin/casual-queue-manager-archive',
[
    make.Compile( 'source/manager/transform.cpp'),
    make.Compile( 'source/manager/handle.cpp'),
    make.Compile( 'source/manager/state.cpp'),
    make.Compile( 'source/manager/admin/server.cpp'),
])


queue_manager = make.LinkExecutable( 'bin/casual-queue-manager', 
    [
      make.Compile( 'source/manager/main.cpp'),
    ], 
    [ 
     manager_archive,
     common,
     'casual-common', 
     'casual-domain-utility',
     'casual-domain-discovery',
     'casual-serviceframework', 
     ])


install_bin.append( queue_manager)



queue_api = make.LinkLibrary( 'bin/casual-queue-api', 
   [
       make.Compile( 'source/api/queue.cpp'),
   ],
   [
    common, 
    'casual-serviceframework', 
    'casual-common', 
    ])

install_lib.append( queue_api)

# c-api
queue_c_api = make.LinkLibrary( 'bin/casual-queue-c-api', 
   [
       make.Compile( 'source/c/queue.cpp'),
   ],
   [
    queue_api,
    common,
    'casual-common', 
    ])

install_lib.append( queue_c_api)



make.Install( 'include/casual/queue/c/queue.h',  dsl.paths().install + '/include/casual/queue/c/')

# forward
forward_server = make.LinkExecutable( 'bin/casual-queue-forward-group',
[
    make.Compile( 'source/forward/handle.cpp'),
    make.Compile( 'source/forward/state.cpp'),
    make.Compile( 'source/forward/main.cpp'),
],
[ common, 'casual-common', 'casual-buffer'])

install_bin.append( forward_server)


# Client
target = make.LinkLibrary( 'bin/casual-queue-admin-cli', 
    [
        make.Compile( 'source/manager/admin/cli.cpp'),
     ], 
   [common, queue_api, 'casual-cli', 'casual-common', 'casual-serviceframework'])
 
install_lib.append( target)


# tools

target = make.LinkExecutable( 'bin/casual-queue-upgrade',
   [
      make.Compile( 'tools/source/upgrade.cpp')
   ],
   [ common, 'casual-common', 'sqlite3'])

install_bin.append( target)

# Unittest

unittest_utility_archive = make.LinkArchive( 'bin/casual-queue-unittest',
    [
        make.Compile( 'unittest/source/utility.cpp'),
    ]
)

test_casual_queue = make.LinkUnittest( 'unittest/bin/test-casual-queue', 
    [
        make.Compile( 'unittest/source/manager/test_transform.cpp'),
        make.Compile( 'unittest/source/group/test_queuebase.cpp'),
        make.Compile( 'unittest/source/test_queue.cpp'),
        make.Compile( 'unittest/source/api/test_c.cpp'),
        make.Compile( 'unittest/source/test_forward.cpp')
    ],
    [
     group_archive,
     manager_archive,
     common,
     queue_api,
     queue_c_api,
     unittest_utility_archive,
     'casual-common',
     'casual-serviceframework',
     'casual-configuration',
     'sqlite3',
     'casual-unittest',
     'casual-service-unittest',
     'casual-domain-unittest',
     'casual-xatmi',
     ]  
)

# Make sure the executables is linked before unittest
make.Dependencies( test_casual_queue, [ queue_manager, queue_group, forward_server])

# Deprecated Forwards ! 

forward_common = make.LinkArchive( 'bin/casual-queue-forward-common',
    [
       make.Compile( 'source/forward/deprecated/common.cpp'),
    ])

forward_service = make.LinkExecutable( 'bin/casual-queue-forward-service',
    [
        make.Compile( 'source/forward/deprecated/service.cpp'),
    ],
    [ forward_common, common, queue_api, 'casual-common', 'casual-buffer', 'casual-serviceframework'])

forward_queue = make.LinkExecutable( 'bin/casual-queue-forward-queue',
    [
        make.Compile( 'source/forward/deprecated/queue.cpp'),
    ],
    [ forward_common, common, queue_api, 'casual-common', 'casual-buffer'])

install_bin.append( forward_service)
install_bin.append( forward_queue)



make.Install( install_lib,  dsl.paths().install + '/lib')
make.Install( install_bin,  dsl.paths().install + '/bin')



