from casual.middleware.make.dsl import *


IncludePaths( [ 
    'include',
    '../common/include',
    '../cli/include',
    '../configuration/include',
    '../serviceframework/include', 
    '../xatmi/include',
    '../transaction/include',
    '../domain/include',
    '../service/include',
    '../../thirdparty/database/include',
    '$(CASUAL_OPTIONAL_INCLUDE_PATHS)',
])


LibraryPaths( [ 
    'bin',
    '../transaction/bin',
    '../configuration/bin',
    '../serviceframework/bin',
    '../common/bin',
    '../cli/bin',
    '../buffer/bin',
    '../domain/bin',
    '../service/bin',
    '../xatmi/bin',
    '$(CASUAL_OPTIONAL_LIBRARY_PATHS)',
])
    



install_lib = []
install_bin = []

# So we get the local build-rm
Environment( 'PATH', '../tools/bin:$(PATH)')

# Common stuff

common = LinkLibrary( 'bin/casual-queue-common',
   [
    Compile( 'source/common/log.cpp'),
    #Compile( 'source/common/ipc.cpp'),
    Compile( 'source/common/queue.cpp'),
    Compile( 'source/code.cpp'),
   ],
   [ 'casual-common', ])
 
install_lib.append( common)

# Group

group_archive = LinkArchive( 'bin/casual-queue-group-archive',
[
    Compile( 'source/group/state.cpp'),   
    Compile( 'source/group/queuebase.cpp'),
    Compile( 'source/group/queuebase/statement.cpp'),
    Compile( 'source/group/handle.cpp'),
])


queue_group = LinkExecutable( 'bin/casual-queue-group', 
[
    Compile( 'source/group/main.cpp')
],
[
    group_archive,
    common,
    'casual-domain-utility',
    'casual-common',
    'sqlite3',
])
     
 
install_bin.append( queue_group)
 
# Manager

manager_archive = LinkArchive( 'bin/casual-queue-manager-archive',
[
    Compile( 'source/manager/transform.cpp'),
    Compile( 'source/manager/handle.cpp'),
    Compile( 'source/manager/state.cpp'),
    Compile( 'source/manager/admin/server.cpp'),
])


queue_manager = LinkExecutable( 'bin/casual-queue-manager', 
    [
      Compile( 'source/manager/main.cpp'),
    ], 
    [ 
     manager_archive,
     common,
     'casual-common', 
     'casual-domain-utility',
     'casual-domain-discovery',
     'casual-serviceframework', 
     ])


install_bin.append( queue_manager)



queue_api = LinkLibrary( 'bin/casual-queue-api', 
   [
       Compile( 'source/api/queue.cpp'),
   ],
   [
    common, 
    'casual-serviceframework', 
    'casual-common', 
    ])

install_lib.append( queue_api)

# c-api
queue_c_api = LinkLibrary( 'bin/casual-queue-c-api', 
   [
       Compile( 'source/c/queue.cpp'),
   ],
   [
    common,
    queue_api,
    'casual-common', 
    ])

install_lib.append( queue_c_api)
Install( 'include/casual/queue/c/queue.h', '$(CASUAL_HOME)/include/casual/queue/c/')

# forward
forward_server = LinkExecutable( 'bin/casual-queue-forward-group',
[
    Compile( 'source/forward/handle.cpp'),
    Compile( 'source/forward/state.cpp'),
    Compile( 'source/forward/main.cpp'),
],
[ common, 'casual-common', 'casual-buffer'])

install_bin.append( forward_server)


# Client
target = LinkLibrary( 'bin/casual-queue-admin-cli', 
    [
        Compile( 'source/manager/admin/cli.cpp'),
     ], 
   [common, queue_api, 'casual-cli', 'casual-common', 'casual-serviceframework'])
 
install_lib.append( target)


# tools

target = LinkExecutable( 'bin/casual-queue-upgrade',
   [
      Compile( 'tools/source/upgrade.cpp')
   ],
   [ common, 'casual-common', 'sqlite3'])

install_bin.append( target)

# Unittest

test_casual_queue = LinkUnittest( 'unittest/bin/test-casual-queue', 
    [
        Compile( 'unittest/source/manager/test_transform.cpp'),
        Compile( 'unittest/source/group/test_queuebase.cpp'),
        Compile( 'unittest/source/test_queue.cpp'),
        Compile( 'unittest/source/api/test_c.cpp'),
        Compile( 'unittest/source/test_forward.cpp')
    ],
    [
     group_archive,
     manager_archive,
     common,
     queue_api,
     queue_c_api,
     'casual-common',
     'casual-serviceframework',
     'casual-configuration',
     'sqlite3',
     'casual-unittest',
     'casual-service-unittest',
     'casual-domain-unittest',
     'casual-xatmi',
     ]  
)

# Make sure the executables is linked before unittest
Dependencies( test_casual_queue, [ queue_manager, queue_group, forward_server])

# Deprecated Forwards ! 

forward_common = LinkArchive( 'bin/casual-queue-forward-common',
    [
       Compile( 'source/forward/deprecated/common.cpp'),
    ])

forward_service = LinkExecutable( 'bin/casual-queue-forward-service',
    [
        Compile( 'source/forward/deprecated/service.cpp'),
    ],
    [ forward_common, common, queue_api, 'casual-common', 'casual-buffer', 'casual-serviceframework'])

forward_queue = LinkExecutable( 'bin/casual-queue-forward-queue',
    [
        Compile( 'source/forward/deprecated/queue.cpp'),
    ],
    [ forward_common, common, queue_api, 'casual-common', 'casual-buffer'])

install_bin.append( forward_service)
install_bin.append( forward_queue)



Install( install_lib, '$(CASUAL_HOME)/lib')
Install( install_bin, '$(CASUAL_HOME)/bin')



