//!
//! Copyright (c) 2025, The casual project
//!
//! This software is licensed under the MIT license, https://opensource.org/licenses/MIT
//!

#include "common/exception/guard.h"

#include "common/environment.h"
#include "common/environment/expand.h"
#include "common/code/raise.h"
#include "common/code/casual.h"

#include <fstream>

namespace casual
{
   namespace tools::documentation::build
   {
      namespace local
      {
         namespace
         {
            auto source_root()
            {
               if( auto path = common::environment::variable::get< std::filesystem::path>( "CMAKE_SOURCE_DIR"))
                  return *path;

               common::code::raise::error( common::code::casual::invalid_argument, "CMAKE_SOURCE_DIR is not set");
            }

            auto binary_root()
            {
               if( auto path = common::environment::variable::get< std::filesystem::path>( "CMAKE_BINARY_DIR"))
                  return *path;

               common::code::raise::error( common::code::casual::invalid_argument, "CMAKE_BINARY_DIR is not set");
            }

            auto compose_path( std::string_view name)
            {
               return local::binary_root() / "middleware" / "tools" / "bin" / name;
            } 

            auto executable_path()
            {
               return compose_path( "casual-build-executable");
            }

            auto server_path()
            {
               return compose_path( "casual-build-server");
            }

            std::vector< common::environment::Variable> environment()
            {
               return { 
                  //common::string::compose( "PATH=", common::environment::expand( "${CMAKE_BINARY_DIR}/middleware/tools/bin:${PATH}"))
               };
            }

            auto execute_help( const std::filesystem::path& path)
            {
               auto capture = common::process::execute( path, { "--color", "false", "--help"}, environment());

               if( ! capture)
                  common::code::raise::error( common::code::casual::invalid_argument, "failed to execute ", path);

               return capture.standard.out;
            }

            auto generate_documentation( const std::filesystem::path& output, const std::filesystem::path& executable)
            {
               std::ofstream out{ output, std::ios::trunc};

               if( ! out)
                  common::code::raise::error( common::code::casual::invalid_file, "failed to open output file: ", output);

               out << "# " << executable.filename().string() << R"(

[//]: # (Attention! this is a generated markdown from casual-tools-documentation - do not edit this file!)


```console
)" << "host# " << executable.filename().string() << " --help \n\n";


               out << execute_help( executable) << "\n\n";

               out << "```\n";
            }

            
         } // <unnamed>
      } // local
      
      void main( int argc, const char** argv)
      {
         local::generate_documentation( 
            local::source_root() / "middleware" / "tools" / "documentation" / "build" / "casual-build-executable.development.md",
            local::executable_path());

         local::generate_documentation( 
            local::source_root() / "middleware" / "tools" / "documentation" / "build" / "casual-build-server.development.md",
            local::server_path());

      }

   } // tools::documentation::build
   
} // casual


int main( int argc, const char** argv)
{
   return casual::common::exception::main::cli::guard( [=]()
   {
      casual::tools::documentation::build::main( argc, argv);
   });
} // main

