import casual.make.api as make
import casual.middleware.make.api as dsl


# Install

# domain examples
make.Install( [ 'domain/readme.md'], dsl.paths().install + '/documentation/example/domain')

# single domain example
make.Install( [ 'domain/single/readme.md', 'domain/single/domain.env'], dsl.paths().install + '/documentation/example/domain/single')
make.Install( [ 'domain/single/configuration/domain.yaml'], dsl.paths().install + '/documentation/example/domain/single/configuration')

# multi domain example
make.Install( [ 'domain/multiple/readme.md'], dsl.paths().install + '/documentation/example/domain/multiple')
make.Install( [ 'domain/multiple/diagram/scenario.svg', 'domain/multiple/diagram/scenario.puml'], dsl.paths().install + '/documentation/example/domain/multiple/diagram')

make.Install( [ 'domain/multiple/A/domain.env'], dsl.paths().install + '/documentation/example/domain/multiple/A')
make.Install( [ 'domain/multiple/A/configuration/domain.yaml'], dsl.paths().install + '/documentation/example/domain/multiple/A/configuration')

make.Install( [ 'domain/multiple/B/domain.env'], dsl.paths().install + '/documentation/example/domain/multiple/B')
make.Install( [ 'domain/multiple/B/configuration/domain.yaml'], dsl.paths().install + '/documentation/example/domain/multiple/B/configuration')

