

INCLUDE_PATHS= include \
	../utility/include \
	../xatmi/include \
	$(UNITTEST_INCLUDE_PATH) \


LIBRARY_PATHS= ../xatmi/bin \
	../utility/bin \



Compile( source/server_context.cpp, obj/server_context.o)
Compile( source/service_context.cpp, obj/service_context.o)
Compile( source/calling_context.cpp, obj/calling_context.o)
Compile( source/buffer_context.cpp, obj/buffer_context.o)
Compile( source/ipc.cpp, obj/ipc.o)
Compile( source/queue.cpp, obj/queue.o)


LinkLibrary( casual_common, \
	obj/server_context.o \
	obj/service_context.o \
	obj/calling_context.o \
	obj/buffer_context.o \
	obj/ipc.o \ 
	obj/queue.o \
	,\ 
	casual_utility)

	
	
	
	
//
// unittest
//
Compile( unittest/isolated/source/test_buffer.cpp, unittest/isolated/obj/test_buffer.o)
Compile( unittest/isolated/source/test_ipc.cpp, unittest/isolated/obj/test_ipc.o)
Compile( unittest/isolated/source/test_marshal.cpp, unittest/isolated/obj/test_marshal.o)
Compile( unittest/isolated/source/test_queue.cpp, unittest/isolated/obj/test_queue.o)
Compile( unittest/isolated/source/test_message_dispatch.cpp, unittest/isolated/obj/test_message_dispatch.o)



LinkIsolatedUnittest( casual_common_isolated, \
	unittest/isolated/obj/test_buffer.o \
	unittest/isolated/obj/test_ipc.o \
	unittest/isolated/obj/test_marshal.o \
	unittest/isolated/obj/test_queue.o \
	unittest/isolated/obj/test_message_dispatch.o, \
	casual_utility casual_common )	

