import casual.make.api as make
import casual.middleware.make.api as dsl

make.IncludePaths( [
   'include',
   'unittest/include',
	'../common/include',
   '../service/include',
   '../transaction/include',
   '../xatmi/include',
   ]
    + make.optional_include_paths()
    + dsl.paths().include.gtest
   )

make.LibraryPaths( [
    'bin',
    '../common/bin',
    '../manager/bin',
    '../domain/bin',
    '../transaction/bin',
    '../service/bin',
    '../configuration/bin'
    ]
    + make.optional_library_paths()
    + dsl.paths().library.gtest
   )

install_libs = []

server_lib = make.LinkLibrary( 'bin/casual-server',
   [
      make.Compile( 'source/context.cpp'),
      make.Compile( 'source/service.cpp'),


      make.Compile( 'source/start.cpp'),
      make.Compile( 'source/executable/start.cpp'),

      make.Compile( 'source/service/protocol.cpp'),
   ],
   [
      'casual-common',
      'casual-service',
      'casual-transaction',
   ])

install_libs.append( server_lib)


test_server = make.LinkUnittest( 'bin/casual-server-test',
   [
      make.Compile( 'unittest/source/test_arguments.cpp'),
      make.Compile( 'unittest/source/test_service.cpp'),
   ],
   [
      server_lib,
      'casual-unittest',
      'casual-common',
      'casual-service',
   ])


make.Install( install_libs, dsl.paths().install + '/lib')
