import casual.make.api as make

make.Build( 'common/makefile.cmk')
make.Build( 'cli/makefile.cmk')
make.Build( 'serviceframework/makefile.cmk')
make.Build( 'manager/makefile.cmk')

make.Build( 'configuration/makefile.server.cmk')

make.Build( 'domain/makefile.server.cmk') 
make.Build( 'transaction/makefile.server.cmk')
make.Build( 'service/makefile.cmk')

make.Build( 'server/makefile.cmk')

make.Build( 'configuration/makefile.client.cmk')
make.Build( 'domain/makefile.client.cmk') 
make.Build( 'transaction/makefile.client.cmk')

make.Build( 'tools/makefile.server.cmk')

# here we can build xatmi...
make.Build( 'xatmi/makefile.cmk')
make.Build( 'buffer/makefile.cmk')
# examples, used for testing below
make.Build( 'example/makefile.cmk')

make.Build( 'event/makefile.cmk')
make.Build( 'file/makefile.cmk')
make.Build( 'queue/makefile.cmk')
make.Build( 'binding/makefile.cmk')
make.Build( 'http/makefile.cmk')

# depends on domain, queue, service
make.Build( 'gateway/makefile.cmk')

make.Build( 'tools/makefile.client.cmk')


# admin cli
make.Build( 'administration/makefile.cmk')

make.Build( 'http/source/inbound/nginx/plugin/makefile.cmk')




