from casual.make.functiondefinitions import *



SetIncludePaths( [ 
    'include',
    '../common/include',
    '../configuration/include',
    '../serviceframework/include', 
    '../thirdparty/database/include',
    '../xatmi/include',
    '$(UNITTEST_INCLUDE_PATH)'
    ]);


SetLibraryPaths( [ 
        'bin',
        '../configuration/bin',
        '../common/bin',
    ]);
    


#
# Common stuff
#
casual_queue_common_obj = [
   Compile( 'source/environment.cpp', 'obj/environment.o'),
];


LinkLibrary( 'casual-queue-common',
    casual_queue_common_obj,
    [ 'casual-common', ]
    );
 


#
# Server
#

casual_queue_server_archive_objs = [
   Compile( 'source/server/server.cpp', 'obj/server/server.o'),
   Compile( 'source/server/database.cpp', 'obj/server/database.o'),
   Compile( 'source/server/handle.cpp', 'obj/server/handle.o')
];


LinkArchive( 'casual-queue-server-archive',
    casual_queue_server_archive_objs
    )


LinkExecutable( 'casual-queue-server', 
    [Compile( 'source/server/main.cpp', 'obj/server/main.o')], 
    [
     'casual-queue-server-archive',
     'casual-queue-common',
     'casual-common',
     'sqlite3',
     ]);
     
 
 
 
#
# Broker
#

casual_queue_broker_archive_objs = [
   Compile( 'source/broker/broker.cpp', 'obj/broker/broker.o'),
   Compile( 'source/broker/handle.cpp', 'obj/broker/handle.o'),
];

LinkArchive( 'casual-queue-broker-archive',
    casual_queue_broker_archive_objs
    )

LinkExecutable( 'casual-queue-broker', 
    [Compile( 'source/broker/main.cpp', 'obj/broker/main.o')], 
    ["casual-queue-broker-archive"]);



#
# rm
#
casual_queue_xa_objs = [
    Compile( 'source/rm/switch.cpp', 'obj/rm/switch.o'),
];     

LinkLibrary( 'casual-queue-rm',
    casual_queue_xa_objs,       
     ['casual-common',
      ]);


#
# Client API
#
casual_queue_api_objs = [
       Compile( 'source/queue.cpp', 'obj/queue.o')
     ];

LinkLibrary( 'casual-queue', 
    casual_queue_api_objs,
    [ 'casual-common' ]
    )


#
# Unittest
#
casual_queue_unittest_objs = [
  Compile( 'unittest/isolated/source/test_server_database.cpp', 'obj/unittest/test_server_database.o'),
  ];

LinkIsolatedUnittest( 'test-casual-queue', 
    casual_queue_unittest_objs,
    [
     'casual-queue-server-archive',
     'casual-common',
     'sqlite3',
     ]  
);

#
# Make sure the binaries is linked before unittest
#
Dependencies( 'test-casual-queue', ['casual-queue-broker', 'casual-queue-server'])








