from casual.make.functiondefinitions import *



SetIncludePaths( [ 
    'include',
    '../common/include',
    '../configuration/include',
    '../serviceframework/include', 
    '../thirdparty/database/include',
    '../xatmi/include',
    '$(UNITTEST_INCLUDE_PATH)'
    ]);


SetLibraryPaths( [ 
        'bin',
        '../configuration/bin',
        '../common/bin',
    ]);
    


#
# Common stuff
#
casual_queue_common_obj = [
   Compile( 'source/environment.cpp', 'obj/environment.o'),
];


LinkLibrary( 'bin/casual-queue-common',
    casual_queue_common_obj,
    [ 'casual-common', ]
    );
 


#
# Group
#

casual_queue_server_archive_objs = [
   Compile( 'source/group/group.cpp', 'obj/group/group.o'),
   Compile( 'source/group/database.cpp', 'obj/group/database.o'),
   Compile( 'source/group/handle.cpp', 'obj/group/handle.o')
];


LinkArchive( 'bin/casual-queue-group-archive',
    casual_queue_server_archive_objs
    )


target_casual_queue_group = LinkExecutable( 'bin/casual-queue-group', 
    [Compile( 'source/group/main.cpp', 'obj/group/main.o')], 
    [
     'casual-queue-group-archive',
     'casual-queue-common',
     'casual-common',
     'sqlite3',
     ]);
     
 
 
 
#
# Broker
#

casual_queue_broker_archive_objs = [
   Compile( 'source/broker/broker.cpp', 'obj/broker/broker.o'),
   Compile( 'source/broker/handle.cpp', 'obj/broker/handle.o'),
];

LinkArchive( 'bin/casual-queue-broker-archive',
    casual_queue_broker_archive_objs
    )


target_casual_queue_broker = LinkExecutable( 'bin/casual-queue-broker', 
    [Compile( 'source/broker/main.cpp', 'obj/broker/main.o')], 
    ["casual-queue-broker-archive"]);



#
# rm
#
casual_queue_xa_objs = [
    Compile( 'source/rm/switch.cpp', 'obj/rm/switch.o'),
];     

LinkLibrary( 'bin/casual-queue-rm',
    casual_queue_xa_objs,       
     ['casual-common',
      ]);


#
# Client API
#
casual_queue_api_objs = [
       Compile( 'source/queue.cpp', 'obj/queue.o')
     ];

LinkLibrary( 'bin/casual-queue', 
    casual_queue_api_objs,
    [ 'casual-common' ]
    )


#
# Unittest
#
casual_queue_unittest_objs = [
  Compile( 'unittest/isolated/source/test_group_database.cpp', 'obj/unittest/test_group_database.o'),
  ];

target_test_casual_queue = LinkIsolatedUnittest( 'unittest/bin/test-casual-queue', 
    casual_queue_unittest_objs,
    [
     'casual-queue-group-archive',
     'casual-common',
     'sqlite3',
     ]  
);

#
# Make sure the executables is linked before unittest
#
Dependencies( target_test_casual_queue, [ target_casual_queue_broker, target_casual_queue_group])








