from casual.make.functiondefinitions import *



IncludePaths( [ 
    'include',
    '../common/include',
    '../configuration/include',
    '../serviceframework/include', 
    '../thirdparty/database/include',
    '../xatmi/include',
    '../transaction/include',
    '$(UNITTEST_INCLUDE_PATH)'
    ]);


LibraryPaths( [ 
        'bin',
        '../transaction/bin',
        '../configuration/bin',
        '../serviceframework/bin',
        '../common/bin',
        '../xatmi/bin',
    ]);
    



install_lib = []
install_bin = []

#
# Common stuff
#

common = LinkLibrary( 'bin/casual-queue-common',
   [
    Compile( 'source/environment.cpp', 'obj/environment.o'),
    Compile( 'source/transform.cpp', 'obj/transform.o'),
   ],
   [ 'casual-common', ]);
 
install_lib.append( common);

#
# Group
#

group_archive = LinkArchive( 'bin/casual-queue-group-archive',
    [
   Compile( 'source/group/group.cpp', 'obj/group/group.o'),
   Compile( 'source/group/database.cpp', 'obj/group/database.o'),
   Compile( 'source/group/handle.cpp', 'obj/group/handle.o')
])


queue_group = LinkExecutable( 'bin/casual-queue-group', 
    [Compile( 'source/group/main.cpp', 'obj/group/main.o')], 
    [
     group_archive,
     common,
     'casual-common',
     'sqlite3',
     ]);
     
 
install_bin.append( queue_group);
 
#
# Broker
#

broker_archive = LinkArchive( 'bin/casual-queue-broker-archive',
   [
     Compile( 'source/broker/broker.cpp', 'obj/broker/broker.o'),
     Compile( 'source/broker/handle.cpp', 'obj/broker/handle.o'),
    
   ])


queue_broker = LinkExecutable( 'bin/casual-queue-broker', 
    [
      Compile( 'source/broker/main.cpp', 'obj/broker/main.o'),
      Compile( 'source/broker/admin/server.cpp', 'obj/broker/admin/server.o'),
    ], 
    [ broker_archive, common, 'casual-common', 'casual-configuration', 'casual-sf', 'casual-xatmi']);


install_bin.append( queue_broker);

#
# rm
#  
rm = LinkLibrary( 'bin/casual-queue-rm',
    [
     Compile( 'source/rm/switch.cpp', 'obj/rm/switch.o'),
    ],       
     [ common,
      'casual-common',
      ]);


install_lib.append( rm);

#
# Client API
#

queue_api = LinkLibrary( 'bin/casual-queue', 
   [
       Compile( 'source/queue.cpp', 'obj/queue.o')
   ],
   [ common, rm, 'casual-common', 'casual-xatmi'])

install_lib.append( queue_api);


#
# Client
#
queue_client = LinkExecutable( 'bin/casual-queue-admin', 
    [
        Compile( 'source/broker/admin/client.cpp', 'obj/broker/admin/client.o'),
     ], 
   [common, queue_api, 'casual-common', 'casual-sf'])


install_bin.append( queue_client);



Environment( 'CASUAL_LOG', '')

resource_proxy = LinkResourceProxy( 'bin/casual-queue-resource-proxy', 'casual-queue-rm', [ rm])

install_bin.append( resource_proxy);



#
# Unittest
#

test_casual_queue = LinkIsolatedUnittest( 'unittest/bin/test-casual-queue', 
    [
     Compile( 'unittest/isolated/source/test_group_database.cpp', 'obj/unittest/test_group_database.o'),
     Compile( 'unittest/isolated/source/test_transform.cpp', 'obj/unittest/test_transform.o'),
    ],
    [
     group_archive,
     common,
     'casual-common',
     'casual-sf',
     'sqlite3',
     ]  
);


#
# Make sure the executables is linked before unittest
#
Dependencies( test_casual_queue, [ queue_broker, queue_group])







Install( install_lib, '$(CASUAL_HOME)/lib')
Install( install_bin, '$(CASUAL_HOME)/bin')



