from casual.make.entity.target import Recipe
import casual.make.entity.model as model
import casual.make.api as make

import subprocess
import os

def perform_build(dummy):
   print( f"building and installing nginx - source root: {os.getenv('CASUAL_MAKE_SOURCE_ROOT')}, build root: {os.getenv('CASUAL_MAKE_BUILD_ROOT')}")
   filename = os.path.join( os.getenv("CASUAL_MAKE_SOURCE_ROOT"), 'thirdparty/setup/install_nginx.py')
   try:
      out = subprocess.check_output(["python3", filename])
   except subprocess.CalledProcessError as e:
      print(e)
      raise

   print(out.decode())

# main - register function
model.register( 'nginx').execute(True).serial(True).add_recipe( Recipe( perform_build, None))


