import casual.make.api as make
import casual.middleware.make.api as dsl

import os

make.IncludePaths( [ 
   'include',
   'unittest/include',
   '../common/include',
   '../cli/include',
   '../configuration/include',
   '../manager/include',
   '../service/include',
   '../service/unittest/include',
   '../transaction/include',
   '../xatmi/include',
   '../domain/unittest/include',
   ]
   + dsl.paths().include.gtest
)


make.LibraryPaths( 
   [ 
      'bin',
      '../common/bin',
      '../cli/bin',
      '../manager/bin',
      '../domain/bin',
      '../configuration/bin',
      '../service/bin',
      '../transaction/bin',
      '../xatmi/bin',
   ]
   + make.optional_library_paths()
   + dsl.paths().library.gtest
)
    

install_lib = []
install_bin = []

# So we get the local build-rm
make.Environment( 'PATH', '../tools/bin' + os.pathsep + os.getenv('PATH'))

common_archive = make.LinkArchive( 'bin/casual-file-common', 
   [
      make.Compile( 'source/instance.cpp'),
   ]
)


file_manager = make.LinkExecutable( 'bin/casual-file-manager', 
   [
      make.Compile( 'source/manager/main.cpp'),
      make.Compile( 'source/manager/handle.cpp'),
      make.Compile( 'source/manager/resource.cpp'),   
      make.Compile( 'source/manager/state.cpp'),
      make.Compile( 'source/manager/admin/server.cpp'),
   ], 
   [ 
      common_archive,
      'casual-common',
      'casual-manager',
   ]
)

install_bin.append( file_manager)


file_api = make.LinkLibrary( 'bin/casual-file-api', 
   [
      make.Compile( 'source/code.cpp'),
      make.Compile( 'source/api/file.cpp'),
   ],
   [
      common_archive,
      'casual-common',
      'casual-transaction',
   ])

install_lib.append( file_api)

file_c_api = make.LinkLibrary( 'bin/casual-file-c-api', 
   [
      make.Compile( 'source/api/c/file.cpp'),
   ],
   [
      file_api,
      'casual-common',
   ])

install_lib.append( file_c_api)


file_cli = make.LinkLibrary( 'bin/casual-file-admin-cli', 
   [
      make.Compile( 'source/manager/admin/cli.cpp'),
   ], 
   [
      common_archive,
      file_api, 
      'casual-cli', 
      'casual-common', 
      'casual-service'])
 
install_lib.append( file_cli)


test_casual_file = make.LinkUnittest( 'unittest/bin/test-casual-file', 
   [
      make.Compile( 'unittest/source/resource/utility.cpp'),
      make.Compile( 'unittest/source/resource/test_resource.cpp'),
   ],
   [
      file_api,
      'casual-common',
      'casual-unittest',
      'casual-domain-unittest',
      'casual-xatmi',
      'casual-service',
      'casual-service-unittest',
      'casual-transaction',
   ]  
)

make.Dependencies( 
   test_casual_file, 
   install_bin,
   )

make.Install( install_lib,  dsl.paths().install + '/lib')
make.Install( install_bin,  dsl.paths().install + '/bin')
