#! /bin/bash

if (( $# < 1 ))
then
    echo "usage: $0 casual_build_version"
    exit -1
fi

CURRENT_DIRECTORY=$( cd "$(dirname "$0")" ; pwd -P )

export CASUAL_BUILD_VERSION=$1

source scl_source enable gcc-toolset-14

bash ${CURRENT_DIRECTORY}/../common/build
