

INCLUDE_PATHS= include \
	../common/include \
	../xatmi/include 

LIBRARY_PATHS = ../common/bin

Compile( source/casual_broker.cpp, obj/casual_broker.o)
Compile( source/casual_broker_main.cpp, obj/casual_broker_main.o)


LinkExecutable( casual_broker, \
	obj/casual_broker.o \
	obj/casual_broker_main.o, \
	casual-common)
