from casual.make.directive import *


IncludePaths( ['include', 'current'])

LinkArchive('bin/gtest', [ Compile('current/src/gtest-all.cc')])
LinkArchive( 'bin/gtest_main', [ Compile('current/src/gtest_main.cc')])

