from casual.make.functiondefinitions import *

INCLUDE_PATHS = ['include', 'current']

SetIncludePaths( INCLUDE_PATHS)

Compile('current/src/gtest-all.cc','obj/gtest-all.o')
Compile('current/src/gtest_main.cc','obj/gtest_main.o')

LinkArchive('gtest',
	['obj/gtest-all.o',
	'obj/gtest_main.o'])