from casual.middleware.make.dsl import *

IncludePaths( ['include',
	'../common/include',
	'../serviceframework/include',
	'../xatmi/include',
	'../queue/include',
	'../buffer/include',
	'$(CASUAL_OPTIONAL_INCLUDE_PATHS)',
    ])
LibraryPaths( [ 'bin',
	'../xatmi/bin',
	'../common/bin',
	'../queue/bin',
	'../buffer/bin',
    '../eventually/bin',
	'../serviceframework/bin',
    '../configuration/bin',
	'$(CASUAL_OPTIONAL_LIBRARY_PATHS)',
	])



install_bin = []



target = LinkExecutable( 'bin/test_multicall_client',
	[
		Compile( 'source/test_multicall.cpp')
	], ['casual-common', 'casual-xatmi', 'casual-serviceframework'])

install_bin.append( target)


# mockup string server 
target = LinkExecutable( 'bin/casual-test-mockup-string-server',
	[
		Compile( 'source/mockup/string/server.cpp')
	], 
   ['casual-common', 'casual-xatmi', 'casual-serviceframework'],
)
	
Install( [ target],'$(CASUAL_HOME)/test/bin')

	

#
# Install
#
Install( install_bin,'$(CASUAL_HOME)/bin')







	
	
