name: Build Casual - Release
on: 
  push:
    branches:
      - 'release/*'

env:
  build_type: normal
  ubi_image: casual/ubi8-builder

jobs:
  calculate-version: 
    runs-on: self-hosted
    outputs:
      major_minor: ${{ steps.major_minor.outputs.value }}
      base_version: ${{ steps.base_version.outputs.value }}
      build_version: ${{ steps.build_version.outputs.value }}
      casual_version: ${{ steps.casual_version.outputs.value }}
      casual_release: ${{ steps.casual_release.outputs.value }}
    steps:
      - name: check out repository casual
        uses: actions/checkout@v4
        with:
          path: 'casual'
          fetch-depth: 0

      - name: retrieve major/minor from branch
        uses: kaisugi/action-regex-match@v1.0.1
        id: regex-match
        with:
          text: ${{ github.ref }}
          regex: '^.*/([0-9.]+)$'

      - name: set major/minor-version
        id: major_minor
        run: echo "value=${{ steps.regex-match.outputs.group1 }}" >> $GITHUB_OUTPUT

      - name: set base_version
        id: base_version
        run: |
          cd ${{ github.workspace }}/casual
          echo "value=$( ${{ github.workspace }}/casual/pipeline/script/version.py ${{ steps.regex-match.outputs.group1 }} ${{ env.build_type}} )" >> $GITHUB_OUTPUT

      - name: normalized branch
        id: normalized_branch
        run: echo "value=$( echo ${{ github.ref }} | sed -E -e 's/refs\/heads\/feature\/[0-9.]+\///g' -e 's/-/_/g' -e 's/\//_/g' )" >> $GITHUB_OUTPUT

      - name: set build_version
        id: build_version
        run: |
          echo "value=${{ steps.base_version.outputs.value }}" >> $GITHUB_OUTPUT

      - name: set casual_version
        id: casual_version
        run: |
          echo "value=${{ steps.build_version.outputs.value }}" >> $GITHUB_OUTPUT

      - name: set casual_release
        id: casual_release
        run: |
          echo "value=1" >> $GITHUB_OUTPUT
  
  notification-start:
    runs-on: ubuntu-latest
    needs: [calculate-version]
    steps:  
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "Starting a new build, Repo: ${{ github.repository }}, Branch: ${{ github.ref_name }}, Version: ${{ needs.calculate-version.outputs.build_version }}, URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"           
  
  build-ubi:
    runs-on: [self-hosted, builder]
    if: ${{ success() }}
    needs: [calculate-version,notification-start]
    env:
      DISTRIBUTION: 'ubi'
    steps:
      - name: check out repository casual
        uses: actions/checkout@v4
        with:
          path: 'casual'
          fetch-depth: 0

      - name: prepare build-script
        run: |
          cat << EOD > builder.sh
          #! /bin/bash

          git config --global --add safe.directory /git/casual/casual

          mkdir /git/casual/casual/results && chmod 777 /git/casual/casual/results

          source /git/casual/casual/pipeline/script/pipeline.env

          export CASUAL_COMMIT_HASH=${{ github.sha }}

          bash /git/casual/casual/pipeline/script/pre/cleanup
          
          touch /git/casual/casual.log
          chmod 777 /git/casual/casual.log

          echo "set(CPACK_RPM_PACKAGE_VERSION ${{ needs.calculate-version.outputs.casual_version }})" > /git/casual/casual/version.cmake
          echo "set(CPACK_RPM_PACKAGE_RELEASE ${{ needs.calculate-version.outputs.casual_release }})" >> /git/casual/casual/version.cmake

          cat /git/casual/casual/version.cmake

          bash /git/casual/casual/pipeline/script/backend/$DISTRIBUTION/build ${{ needs.calculate-version.outputs.build_version }}
          CODE=$?

          find /tmp/build/casual -name 'casual-middleware-*.rpm' -exec cp "{}" /git/casual/casual/results  \;
          find /tmp/build/casual -name 'report.xml' -exec cp "{}" /git/casual/casual/results  \;
          chmod 777 /git/casual/casual/results/*

          bash /git/casual/casual/pipeline/script/post/cleanup

          exit $CODE

          EOD

          chmod +x builder.sh

      - name: Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/git/casual:Z -i ${{ env.ubi_image}}:${{ needs.calculate-version.outputs.major_minor }}-cmake

      - name: Logpublisher
        if: ${{ failure() || cancelled() }}
        run: |
          ${{ github.workspace }}/casual/pipeline/script/post/logpublisher ${{ github.workspace }}/casual.log ${DISTRIBUTION}-${{ needs.calculate-version.outputs.build_version }}

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ success() || failure() }}   # run this step even if previous step failed
        with:
          name: Google Tests - Ubi # Name of the check run which will be created
          path: ./**/report.xml       # Path to test results
          reporter: java-junit        # Format of test result
          working-directory: casual

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubi_rpm
          path: ./**/casual-middleware*.rpm

  tag-repo:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [calculate-version,build-ubi]
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ needs.calculate-version.outputs.build_version }}
          tag_prefix: ""

  publish-version:
    runs-on: [self-hosted, casual, publish]
    needs: [build-ubi,tag-repo]
    if: ${{ success() }}
    steps:
      - name: Publish ubi
        uses: actions/download-artifact@v4
        with:
          name: ubi_rpm
          path: /var/www/release/
      - name: Move rpm to right location
        run: |
          mv /var/www/release/casual/results/*.rpm /var/www/release/
          rm -rf /var/www/release/casual

  build-casual-image:
    runs-on: [self-hosted, builder]
    needs: [calculate-version,build-ubi,publish-version]
    if: ${{ success() }}
    steps:
      - name: check out repository casual
        uses: actions/checkout@v4
        with:
          path: 'casual'
          fetch-depth: 0
      - name: Download ubi
        uses: actions/download-artifact@v4
        with:
          name: ubi_rpm
          path: ${{ github.workspace }}/casual/pipeline/script/image-build/
      - name: set rpmfile name
        id: rpmfile
        run: echo "value=$( ls -1t ${{ github.workspace }}/casual/pipeline/script/image-build/casual | head -1 )" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: CASUAL_RPM=casual/${{steps.rpmfile.outputs.value}}
          context: ${{ github.workspace }}/casual/pipeline/script/image-build/
          tags: casual/middleware:${{ needs.calculate-version.outputs.build_version }}

  notification-end:
    runs-on: ubuntu-latest
    needs: [calculate-version,build-ubi,tag-repo,publish-version,build-casual-image]
    if: ${{ always() }}
    steps: 
      - uses: martialonline/workflow-status@v4
        id: check
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "Build status ${{ steps.check.outputs.status }}, Repo: ${{ github.repository }}, Branch: ${{ github.ref_name }}, Version: ${{ needs.calculate-version.outputs.build_version }}, URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"           
