name: Build Casual - Alpha
on: 
  push:
    branches:
      - 'feature/**'
      - '!feature/*/main'
      - 'patch/**'
      - '!patch/*/main'
env:
  release-type: alpha
  ubi_image: casual/ubi8-builder

jobs:
  calculate-version:
    runs-on: ubuntu-latest
    outputs:
      major-minor: ${{ steps.version.outputs.major-minor }}
      build-version: ${{ steps.version.outputs.build-version }}
      casual-version: ${{ steps.version.outputs.casual-version }}
      casual-release: ${{ steps.version.outputs.casual-release }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: casualcore/casual-version@0.1
        id: version
        with:
          release-type: ${{ env.release-type }}
  
  notification-start:
    runs-on: ubuntu-latest
    needs: [calculate-version]
    steps:  
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "Starting a new build, Repo: ${{ github.repository }}, Branch: ${{ github.ref_name }}, Version: ${{ needs.calculate-version.outputs.build-version }}, URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"           
  
  build-ubi:
    runs-on: [self-hosted, builder]
    if: ${{ success() }}
    needs: [calculate-version,notification-start]
    env:
      DISTRIBUTION: 'ubi'
    steps:
      - name: check out repository casual
        uses: actions/checkout@v6
        with:
          path: 'casual'
          fetch-depth: 0

      - name: prepare build-script
        run: |
          cat << EOD > builder.sh
          #! /bin/bash

          git config --global --add safe.directory /git/casual/casual

          mkdir /git/casual/casual/results && chmod 777 /git/casual/casual/results

          source /git/casual/casual/pipeline/script/pipeline.env

          export CASUAL_COMMIT_HASH=${{ github.sha }}

          bash /git/casual/casual/pipeline/script/pre/cleanup
          
          touch /git/casual/casual.log
          chmod 777 /git/casual/casual.log

          mkdir -p \${CMAKE_BINARY_DIR}
          echo "set(CPACK_RPM_PACKAGE_VERSION ${{ needs.calculate-version.outputs.casual-version }})" > \${CMAKE_BINARY_DIR}/version.cmake
          echo "set(CPACK_RPM_PACKAGE_RELEASE ${{ needs.calculate-version.outputs.casual-release }})" >> \${CMAKE_BINARY_DIR}/version.cmake

          cat \${CMAKE_BINARY_DIR}/version.cmake

          bash /git/casual/casual/pipeline/script/backend/$DISTRIBUTION/build ${{ needs.calculate-version.outputs.build-version }}
          CODE=$?

          find \${CMAKE_BINARY_DIR} -name 'casual-middleware-*.rpm' -exec cp "{}" /git/casual/casual/results  \;
          find \${CMAKE_BINARY_DIR} -name 'report.xml' -exec cp "{}" /git/casual/casual/results  \;
          chmod 777 /git/casual/casual/results/*

          bash /git/casual/casual/pipeline/script/post/cleanup

          exit $CODE

          EOD

          chmod +x builder.sh

      - name: Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/git/casual:Z -i ${{ env.ubi_image}}:${{ needs.calculate-version.outputs.major-minor }}-cmake

      - name: Logpublisher
        if: ${{ failure() || cancelled() }}
        run: |
          ${{ github.workspace }}/casual/pipeline/script/post/logpublisher ${{ github.workspace }}/casual.log ${DISTRIBUTION}-${{ needs.calculate-version.outputs.build-version }}

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ success() || failure() }}    # run this step even if previous step failed
        with:
          name: Google Tests - Ubi # Name of the check run which will be created
          path: ./**/report.xml       # Path to test results
          reporter: java-junit        # Format of test result
          working-directory: casual

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubi_rpm
          path: ./**/casual-middleware*.rpm


  notification-end:
    runs-on: ubuntu-latest
    needs: [calculate-version,build-ubi]
    if: ${{ always() }}
    steps: 
      - uses: martialonline/workflow-status@v4
        id: check
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "Build status ${{ steps.check.outputs.status }}, Repo: ${{ github.repository }}, Branch: ${{ github.ref_name }}, Version: ${{ needs.calculate-version.outputs.build-version }}, URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"           
