#! /bin/bash

find $REPOSITORY_ROOT -name "*.gc*" -print | xargs rm > /dev/null
find $REPOSITORY_ROOT -name "report.xml" -print | xargs rm > /dev/null
rm -rf $REPOSITORY_ROOT/middleware/.casual/unittest/.singleton/.domain-singleton > /dev/null
cd $REPOSITORY_ROOT && casual-make --stat --no-colors clean 

